### ISSUE TITLE
Modulus is negative

### ISSUE THREAD

**Issue by mark--** [russelldavies/jwk-creator#1]
Nice service, but the resulting modulus turns out to be negative which prevents usage.
For example with this public key: 

    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0QokRbKDXR0dRYogCAwX
    0SyqmqwopDi0WkxrLuyhDmUQ6fbuuUqGeDJpUDxv5LxvfJrIFJMzjZz7eq1KYI0o
    FNUU8JY9NGwYuMtEgEzBk8hGH7P6n9jWSPmAkI36o9Ipfl71hgVPTDphHbvYN3bz
    MJTXDCsX07tgoiVJ2LnZDbrBZ/lW2OP3j3pv1YgofFjeDB2WEodRjWtjM52P31xc
    xLZqQ6jpljCdFvUnYO0NLke2AMc3yP6q3816XCsO7W1LIMncuyzFAqbiFaRnDQ47
    HD+M5bha+gyEwxFshTkDszRLDew/IgBfkFY6CcJ5olDCkWKfROd5n9080oldCD4p
    gwIDAQAB
    -----END PUBLIC KEY-----

**Comment by russelldavies** [comment]
The modulus I get from that key is: `0QokRbKDXR0dRYogCAwX0SyqmqwopDi0WkxrLuyhDmUQ6fbuuUqGeDJpUDxv5LxvfJrIFJMzjZz7eq1KYI0oFNUU8JY9NGwYuMtEgEzBk8hGH7P6n9jWSPmAkI36o9Ipfl71hgVPTDphHbvYN3bzMJTXDCsX07tgoiVJ2LnZDbrBZ_lW2OP3j3pv1YgofFjeDB2WEodRjWtjM52P31xcxLZqQ6jpljCdFvUnYO0NLke2AMc3yP6q3816XCsO7W1LIMncuyzFAqbiFaRnDQ47HD-M5bha-gyEwxFshTkDszRLDew_IgBfkFY6CcJ5olDCkWKfROd5n9080oldCD4pgw`

Which, treated as big endian and decoded into decimal is:
`1572895454817757092986260319448859587291074599976449001560754716167589535035294451522744029044274470370858556961616241461515991516993328498222989179658389894999279023493806458575317652362842343578702590750767095188007047562570005675823766236544949739654045895603907713598893255379455181608273966474211919731171265217836472804033762742739551286557828756722716684982155484664674415513420983395665524328979731181058025421018350324960738337699623859056100050282059189646370827124897975305468167602059134021919056782120908441231966698636200394583407527126988659026402286179361491042300440008509958286411999538456963`

What results are you getting?

**Comment by mark--** [comment]
Sorry for the much delayed response! I get the same modulus as you when using the tool. Problem seems to be in the interpretation in the JWK spring lib. But I am really not sure anymore and I am not working in the related project anymore. So you might as well close the issue.
